{{- range $i, $instance := .Values.bitcoind.instances }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $instance.name }}
  target: target: {{ printf "bitcoind-%d" (add $i 1) }}
spec:
  serviceName: "bitcoind"
  replicas: 1
  selector:
    matchLabels:
      app: {{ $instance.name }}
  template:
    metadata:
      labels:
        app: {{ $instance.name }}
    spec:
      containers:
      - name: {{ $instance.name }}
        image: yourregistry/bitcoind:{{ default "0.23.0" $instance.version }}
        ports:
        - containerPort: 8332
        volumeMounts:
        - name: data
          mountPath: /var/lib/bitcoin
        {{- if default true $instance.sidecar_enabled }}
        - name: sidecar
          image: yourregistry/sidecar:latest
          ports:
            - containerPort: 1234
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
{{- end }}
