{{- range .Values.cln.instances }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: scaling-lightning/cln:{{ default "1.0.0" .version }}
          ports:
            - containerPort: 9735
        {{- if default true .sidecar_enabled }}
        - name: sidecar
          image: scaling-lightning/sidecar:latest
          ports:
            - containerPort: 1234
        {{- end }}
---
{{- end }}
